name: test suite
on: [push, pull_request]

jobs:
  test:
    name: nargo test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: noir-lang/noirup@v0.1.2
        with:
          toolchain: 0.22.0
      - run: nargo test